//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaeilgePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GaeilgePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;abacais&quot;:&quot;abacas&quot;,&quot;abacas&quot;:&quot;abacas&quot;,&quot;abacht&quot;:&quot;abacht&quot;,&quot;abachta&quot;:&quot;abacht&quot;,&quot;abach&quot;:&quot;abach&quot;,&quot;abaigh&quot;:&quot;abach&quot;,&quot;abairtí&quot;:&quot;abairt&quot;,&quot;abairte&quot;:&quot;abairt&quot;,&quot;abarlacha&quot;:&quot;abarlach&quot;,&quot;abarlaí&quot;:&quot;abarlach&quot;,&quot;abarlach&quot;:&quot;abarlach&quot;,&quot;abarthacht&quot;:&quot;abarthacht&quot;,&quot;abarthachta&quot;:&quot;abarthacht&quot;,&quot;abair&quot;:&quot;abar&quot;,&quot;abar&quot;:&quot;abar&quot;,&quot;abdómain&quot;:&quot;abdóman&quot;,&quot;abdóman&quot;:&quot;abdóman&quot;,&quot;abhacréaltaí&quot;:&quot;abhacréalta&quot;,&quot;abhacréalta&quot;:&quot;abhacréalta&quot;,&quot;abhaic&quot;:&quot;abhac&quot;,&quot;abhac&quot;:&quot;abhac&quot;,&quot;abhacáid&quot;:&quot;abhacád&quot;,&quot;abhacád&quot;:&quot;abhacád&quot;,&quot;abhlacha&quot;:&quot;abhaill&quot;,&quot;abhla&quot;:&quot;abhaill&quot;,&quot;aibhne [re....
        /// </summary>
        internal static string dictionary {
            get {
                return ResourceManager.GetString("dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;inflection&quot;: {
        ///		&quot;plural&quot;: [
        ///			&quot;a&quot;,
        ///			&quot;í&quot;,
        ///			&quot;ta&quot;,
        ///			&quot;a&quot;,
        ///			&quot;anna&quot;,
        ///			&quot;tha&quot;,
        ///			&quot;ach&quot;,
        ///			&quot;each&quot;,
        ///			&quot;aidh&quot;,
        ///			&quot;aigh&quot;,
        ///			&quot;eanna&quot;,
        ///			&quot;eacha&quot;,
        ///			&quot;acha&quot;,
        ///			&quot;the&quot;,
        ///			&quot;adh&quot;,
        ///			&quot;eadh&quot;
        ///		],
        ///		&quot;eclipsis&quot;: [
        ///			&quot;bp&quot;,
        ///			&quot;dt&quot;,
        ///			&quot;gc&quot;,
        ///			&quot;mb&quot;,
        ///			&quot;nd&quot;,
        ///			&quot;ng&quot;,
        ///			&quot;bhf&quot;,
        ///			&quot;n-&quot;,
        ///			&quot;t-&quot;
        ///		],
        ///		&quot;aspiration&quot;: [
        ///			&quot;bh&quot;,
        ///			&quot;ch&quot;,
        ///			&quot;dh&quot;,
        ///			&quot;fh&quot;,
        ///			&quot;gh&quot;,
        ///			&quot;mh&quot;,
        ///			&quot;ph&quot;,
        ///			&quot;sh&quot;,
        ///			&quot;th&quot;
        ///		]
        ///	},
        ///	&quot;irregular&quot;: {
        ///		&quot;plural&quot;: {
        ///			&quot;mná&quot;: &quot;bean&quot;,
        ///			&quot;deirfi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string grammar {
            get {
                return ResourceManager.GetString("grammar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///
        ///  &quot;excluded&quot;: {
        ///    &quot;article&quot;: [ &quot;na&quot;, &quot;an&quot; ],
        ///    &quot;preposition&quot;: [ &quot;agus&quot;, &quot;ag&quot;, &quot;ar&quot;, &quot;as&quot;, &quot;chun&quot;, &quot;chuig&quot;, &quot;de&quot;, &quot;do&quot;, &quot;den&quot;, &quot;don&quot;, &quot;fara&quot;, &quot;faoi&quot;, &quot;i&quot;, &quot;in&quot;, &quot;idir&quot;, &quot;ionsar&quot;, &quot;le&quot;, &quot;ó&quot;, &quot;roimh&quot;, &quot;trí&quot;, &quot;thar&quot;, &quot;um&quot;, &quot;a&quot;, &quot;dar&quot;, &quot;is&quot;, &quot;gan&quot;, &quot;go&quot;, &quot;godtí&quot;, &quot;go dtí&quot;, &quot;mar&quot;, &quot;os&quot;, &quot;seachas&quot; ],
        ///    &quot;interrogative&quot;: [ &quot;cé&quot;, &quot;cén&quot;, &quot;cá&quot;, &quot;cad&quot;, &quot;conas&quot;, &quot;cathain&quot;, &quot;bhfuil&quot;, &quot;nach&quot;, &quot;nár&quot;, &quot;ar&quot;, &quot;air&quot; ],
        ///    &quot;miscellaneous&quot;: [ &quot;méid&quot;, &quot;mhéid&quot;, &quot;faoin&quot;, &quot;is&quot;, &quot;céi....
        /// </summary>
        internal static string keywordMetadata {
            get {
                return ResourceManager.GetString("keywordMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;static&quot;: {
        ///    &quot;release&quot;: &quot;Eisiúint &quot;,
        ///    &quot;all-groups&quot;: &quot;Gach grúpa&quot;
        ///  },
        ///  &quot;error&quot;: {
        ///    &quot;authentication&quot;: &quot;Fíordheimhniú neamhbhailí. Níl cead isteach.&quot;,
        ///    &quot;create&quot;: &quot;Níor cruthaíodh taifead. Athbhreithnigh an méid a chuir tú isteach.&quot;,
        ///    &quot;delete&quot;: &quot;Níor scriosadh taifead. Athbhreithnigh an rogha a rinne tú.&quot;,
        ///    &quot;duplicate&quot;: &quot;Níor cruthaíodh taifead. Tá taifead dúblach ann cheana. Athbhreithnigh an méid a chuir tú isteach.&quot;,
        ///    &quot;exception&quot;: &quot;Tharla earráid neamhthuartha. Iarr tacaí [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;match&quot;:&quot;ab&quot;,&quot;lemma&quot;:&quot;ab&quot;},{&quot;match&quot;:&quot;abacas&quot;,&quot;lemma&quot;:&quot;abacas&quot;},{&quot;match&quot;:&quot;abacht&quot;,&quot;lemma&quot;:&quot;abacht&quot;},{&quot;match&quot;:&quot;abairt&quot;,&quot;lemma&quot;:&quot;abairt&quot;},{&quot;match&quot;:&quot;abairtín&quot;,&quot;lemma&quot;:&quot;abairt&quot;},{&quot;match&quot;:&quot;frása&quot;,&quot;lemma&quot;:&quot;abairt&quot;},{&quot;match&quot;:&quot;abairt&quot;,&quot;lemma&quot;:&quot;abairtín&quot;},{&quot;match&quot;:&quot;abairtín&quot;,&quot;lemma&quot;:&quot;abairtín&quot;},{&quot;match&quot;:&quot;frása&quot;,&quot;lemma&quot;:&quot;abairtín&quot;},{&quot;match&quot;:&quot;ábaltacht&quot;,&quot;lemma&quot;:&quot;ábaltacht&quot;},{&quot;match&quot;:&quot;acmhainn&quot;,&quot;lemma&quot;:&quot;ábaltacht&quot;},{&quot;match&quot;:&quot;bua&quot;,&quot;lemma&quot;:&quot;ábaltacht&quot;},{&quot;match&quot;:&quot;cumas&quot;,&quot;lemma&quot;:&quot;ábaltacht&quot;},{&quot;match&quot;:....
        /// </summary>
        internal static string synonym {
            get {
                return ResourceManager.GetString("synonym", resourceCulture);
            }
        }
    }
}
