//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishLanguagePlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnglishLanguagePlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;excluded&quot;: {
        ///    &quot;article&quot;: [ &quot;the&quot;, &quot;an&quot;, &quot;a&quot; ],
        ///    &quot;preposition&quot;: [ &quot;of&quot;, &quot;in&quot;, &quot;to&quot;, &quot;for&quot;, &quot;with&quot;, &quot;on&quot;, &quot;at&quot;, &quot;from&quot;, &quot;by&quot;, &quot;about&quot;, &quot;as&quot;, &quot;into&quot;, &quot;like&quot;, &quot;through&quot;, &quot;after&quot;, &quot;over&quot;, &quot;between&quot;, &quot;out&quot;, &quot;against&quot;, &quot;during&quot;, &quot;without&quot;, &quot;before&quot;, &quot;under&quot;, &quot;around&quot;, &quot;among&quot;, &quot;and&quot;, &quot;or&quot; ],
        ///    &quot;interrogative&quot;: [ &quot;how&quot;, &quot;where&quot;, &quot;what&quot;, &quot;why&quot;, &quot;when&quot;, &quot;who&quot;, &quot;which&quot;, &quot;much&quot;, &quot;many&quot; ],
        ///    &quot;miscellaneous&quot;: [ &quot;has&quot;, &quot;have&quot;, &quot;is&quot;, &quot;are&quot;, &quot;not&quot; ],
        ///    &quot;regex&quot;: &quot;[^a-zA-Z\\d\\s]&quot;
        ///  }
        ///}
        ///.
        /// </summary>
        internal static string keywordMetadata {
            get {
                return ResourceManager.GetString("keywordMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;static&quot;: {
        ///    &quot;release&quot;: &quot;Release&quot;,
        ///    &quot;all-groups&quot;: &quot;All Groups&quot;
        ///  },
        ///  &quot;error&quot;: {
        ///    &quot;authentication&quot;: &quot;Invalid authentication. Access denied.&quot;,
        ///    &quot;create&quot;: &quot;No record has been created. Please review your input.&quot;,
        ///    &quot;delete&quot;: &quot;No record has been deleted. Please review your selection.&quot;,
        ///    &quot;duplicate&quot;: &quot;No record has been created. A duplicate record already exists. Please review your input.&quot;,
        ///    &quot;exception&quot;: &quot;An unexpected error has occurred. Please seek technical support.&quot;,
        ///    &quot;i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;match&quot;:&quot;mutilate&quot;,&quot;lemma&quot;:&quot;mutilation&quot;},{&quot;match&quot;:&quot;prank&quot;,&quot;lemma&quot;:&quot;prankster&quot;},{&quot;match&quot;:&quot;hope&quot;,&quot;lemma&quot;:&quot;despair&quot;},{&quot;match&quot;:&quot;ascetically&quot;,&quot;lemma&quot;:&quot;ascetic&quot;},{&quot;match&quot;:&quot;withdraw&quot;,&quot;lemma&quot;:&quot;withdrawer&quot;},{&quot;match&quot;:&quot;Jamaican&quot;,&quot;lemma&quot;:&quot;Jamaica&quot;},{&quot;match&quot;:&quot;ionize&quot;,&quot;lemma&quot;:&quot;ionization&quot;},{&quot;match&quot;:&quot;susceptible&quot;,&quot;lemma&quot;:&quot;susceptibleness&quot;},{&quot;match&quot;:&quot;sorriness&quot;,&quot;lemma&quot;:&quot;sorry&quot;},{&quot;match&quot;:&quot;ascertain&quot;,&quot;lemma&quot;:&quot;ascertainable&quot;},{&quot;match&quot;:&quot;express&quot;,&quot;lemma&quot;:&quot;local&quot;},{&quot;match&quot;:&quot;punt&quot;,&quot;lemma&quot;:&quot;punter&quot;},{&quot;match&quot;:&quot;evade&quot;,&quot;lemma&quot;:&qu....
        /// </summary>
        internal static string synonym {
            get {
                return ResourceManager.GetString("synonym", resourceCulture);
            }
        }
    }
}
